### ISSUE TITLE
Solve dependency installation problem

### ISSUE THREAD

**Issue by IgorPerikov** [prodrink/programma#1]
solve problem with installation of newly added packages etc
probably something connected with [pip freeze](https://pip.pypa.io/en/stable/reference/pip_freeze/)

as a starting point - add to this requirements next packages:
1. [confluent-kafka](https://github.com/confluentinc/confluent-kafka-python#prerequisites)
2. any appropriate telegram bot api

**Comment by MysterionRise** [comment]
Something for later - pull install binary dependencies to docker image with python. https://hub.docker.com/_/python/
